server:
  port: 8081

spring:
  data:
    redis:
      # Redis 服务器地址
      host: localhost
      # Redis 服务器端口
      port: 6379
      # 连接密码（如果设置了密码）
      password:
      # 连接超时时间（毫秒）
      timeout: 5000ms
      # 数据库索引（0 - 15，默认为 0）
      database: 0
      # 连接池配置（使用 Lettuce）
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（负数表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
          # 空闲连接检测周期
          time-between-eviction-runs: 60s

yyyin:
  sms:
   ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c401991cb7de03206f
      accountToken: 62cd45241e1b48a0b725cb98a26d675c
      appId: 2c94811c9860a9c401991cb7df862076
      templateId: 1
